version: '3.8'

services:
  starlink-logstash:
    build: .
    container_name: starlink-logstash
    volumes:
      - ./config/pipeline:/usr/share/logstash/pipeline
      - ./config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml